# Generated by Django 4.2.3 on 2023-08-01 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(db_column='RoleId', primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'UserRole',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('fullname', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('is_deleted', models.BooleanField(default=0)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LawApp.role')),
            ],
            options={
                'db_table': 'NewUserDetails',
            },
        ),
        migrations.CreateModel(
            name='UserPricing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('StartingDate', models.DateTimeField()),
                ('EndingDate', models.DateTimeField()),
                ('NumberOfQueries', models.IntegerField()),
                ('isCurrent', models.BooleanField()),
                ('userid', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('query', models.CharField(db_column='Query', max_length=5000)),
                ('answer', models.CharField(db_column='Answer', max_length=5000)),
                ('userid', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
